name: pacha_website
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  social_media_buttons: ^1.0.0
  google_fonts: ^5.1.0
  visibility_detector: ^0.3.3
  web_smooth_scroll: ^1.1.0
  animated_text_kit: ^4.2.2
  # provider: ^6.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  
  assets:
    - lib/assests/printer.jpg
    - lib/assests/tal.jpg
    - lib/assests/pacha.jpg
    
    - lib/assests/happy_customers.jpg
    
  
  